model:
  resume: False
  use_fp16: True
  amp: True
  lr: 1e-4
  embed_dim: 64
  params:
    lossconfig:
      multiscale: False
      adversarial: True
      disc_weight: 0.5
      epochs: 600
      warmup_epochs: 5
      kl_anneal: False
      kl_max_coeff: 0.1
      kl_const_coeff: 0.0001
      kl_const_portion: 0.0001
      kl_anneal_portion: 0.9
      sn_reg: True
      sn_reg_weight_decay: 1e-1
      sn_reg_weight_decay_anneal: False
      sn_reg_weight_decay_init: 5
      lr_scheduler: False
      save_and_sample_every: 10
      gradient_accumulate_every: 5

    ddconfig:
      double_z: True
      timesformer_channels: 384
      splits: 1
      patch_size: 8
      resolution: 64
      z_channels: 64
      in_channels: 3
      out_ch: 64
      ch: 64
      ch_mult:
      - 1
      - 2
      - 4
      - 8
      num_res_blocks: 2
      attn_resolutions: []
      hdbf_resolutions: [32] #[128, 64]
      inter_attn_resolutions: [32] #[32, 64, 128, 256]
      dropout: 0.0
      attn_type: vanilla-multihead

    mlpconfig:
      in_ch: 2
      out_ch: 3
      ch: 256
      latent_dim: 64

data:
  domain: video
  mode: train
  dataset: SKY
  data_dir: /home/sudhir/Projects/Adobe/CATER/max2action/Data
  save_pth: ./cater_gan_d2c_vae/
  batch_size: 2
  test_batch_size: 4
  frames: 16
